name: Unity HTML5 Build and Deploy

on:
  push:
    branches:
      - main # Replace "main" with the branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"

    - uses: game-ci/unity-builder@v2.2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL

    - name: Build and Deploy HTML5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        unity -batchmode -nographics -silent-crashes -logFile
        -projectPath ./PaddleBall
        -executeMethod BuildScript.PerformBuild
        -quit

        # Move the built files to the dist directory
        mkdir -p dist
        cp -r ./PaddleBall/Builds/HTML5/* ./dist/

        # Deploy the built files to the production branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b production
        git add dist/
        git commit -m "Deploy HTML5 build"
        git push -u origin production

