name: Unity HTML5 Build and Deploy

on:
  push:
    branches:
      - main # Replace "main" with the branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"

    - name: Restore cached Library
      id: cache-library-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          Library
        key: ${{ runner.os }}-Library

    - uses: game-ci/unity-builder@v2.2.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL

    - name: Build and Deploy WEBGL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Deploy the built files to the production branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b production

        #remove the previous build
        git rm -fr .
        git commit -m "Remove previous build."

        # add built files and deploy
        ls ./build/WebGL/WebGL/
        cp -R ./build/WebGL/WebGL/* .
        git add -f ./index.html ./TemplateData/* ./Build
        git commit -m "Deploy new build"
        git push -uf origin production

    - name: Save Library
      id: cache-library-save
      uses: actions/cache/save@v3
      with:
        path: |
          Library
        key: ${{ steps.cache-library-restore.outputs.cache-primary-key }}

