name: Unity HTML5 Build and Deploy

on:
  push:
    branches:
      - main # Replace "main" with the branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"

    - name: Cache Library
      uses: actions/cache@v2
      with:
        path: |
          Library
        key: ${{ runner.os }}-library-${{ hashFiles('**/Packages/manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-library-

    - uses: game-ci/unity-builder@v2.2.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL

    - name: Build and Deploy WEBGL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Deploy the built files to the production branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b production
        git pull --ff-only

        #remove the previous build
        git rm -fr .
        git commit -m "Remove previous build."

        # add built files and deploy
        git add -f ./build/
        git commit -m "Deploy new build"
        git push -u origin production

